#index:
#    path: /
#    controller: App\Controller\DefaultController::index

inicio:
    path: /
    controller: App\Controller\InicioController::index

nosotros:
    path: /nosotros
    controller: App\Controller\NosotrosController::nosotros

productos_por_categoria:
    path: /productos/{categoria}
    controller: App\Controller\ProductosController::productosPorCategoria
    methods: [GET]

productos_por_precio:
  path: /productos/precio/{min}/{max}
  controller: App\Controller\ProductosController::productosPorPrecio

productos_por_nombre:
  path: /productos/buscar
  controller: App\Controller\ProductosController::buscarPorNombre
  methods: GET

producto:
  path: /producto/{codprod}
  controller: App\Controller\ProductosController::show

perfil_usuario:
    path: /perfil
    controller: App\Controller\UsuarioController::verPerfil

